// Generated by CoffeeScript 1.12.6
(function() {
  var calculator, select,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  select = (function() {
    var menu, numA, numB;

    function select() {}

    numA = 6;

    menu = "*";

    numB = 2;

    return select;

  })();

  calculator = (function(superClass) {
    var message;

    extend(calculator, superClass);

    function calculator() {
      return calculator.__super__.constructor.apply(this, arguments);
    }

    message = (function() {
      switch (false) {
        case select.menu !== "+":
          return select.numA + select.numB;
        case select.menu !== "-":
          return select.numA - select.numB;
        case select.menu !== "*":
          return select.numA * select.numB;
        case select.menu !== "/":
          return select.numA / select.numB;
        default:
          return alert("False!!");
      }
    })();

    return calculator;

  })(select);

  select = new sclect();

  calculator = new calculator();

  select();

  alert(calculator());

}).call(this);

//# sourceMappingURL=calculator.js.map
