// Generated by CoffeeScript 1.12.6
(function() {
  var Calculator;

  Calculator = (function() {
    function Calculator() {
      $('#disp').val('');
      this.total = [];
      this.calcList1 = [];
      this.calcList2 = [];
      this.calcList3 = [];
      this.count = 0;
      this.value = '';
      this.result1 = 0;
      this.result2 = 0;
      this.result3 = 0;
      $('.num, .menu').click((function(_this) {
        return function(evt) {
          _this.total.push(evt.target.defaultValue);
          $('#disp').val(_this.total.join(''));
          _this.value += _this.total[_this.count++];
          _this.result1 = _this.value;
          return console.log(_this.result1);
        };
      })(this));
      $('#C').click((function(_this) {
        return function(evt) {
          _this.calcList1.push(evt.target.defaultValue);
          $('#disp').val(_this.total.clear);
          _this.total = [];
          _this.count = 0;
          return _this.value = '';
        };
      })(this));
      $('#equal').click((function(_this) {
        return function(evt) {
          _this.calcList2.push(evt.target.defaultValue);
          $('#disp').val(_this.total.clear);
          _this.result = _this.value;
          return console.log(_this.result);
        };
      })(this));
    }

    return Calculator;

  })();

  new Calculator();

}).call(this);

//# sourceMappingURL=calculator.js.map
